version: "3.9"

services:
  backend:
    container_name: novakit-backend
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8099:8099"
    networks:
      - shared
    volumes:
      - .:/app
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8099
      --reload

networks:
  shared:
    external: true
    name: shared
