global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "novakit-fastapi"
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8099
